name: CI - Backend

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/**'

jobs:
  build-test:
    uses: ./.github/workflows/docker-build.yml
    with:
      service: backend
      path: ./backend
      image: ghcr.io/${{ github.repository_owner }}/linksphere-backend
    secrets: inherit