name: Docker Build

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      path:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      GHCR_PAT:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Docker Build and Tag
        run: |
          IMAGE_LOWER=$(echo "${{ inputs.image }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_LOWER ${{ inputs.path }}
          docker tag $IMAGE_LOWER $(echo "${{ inputs.image }}:latest" | tr '[:upper:]' '[:lower:]')

      - name: Push to GHCR
        run: |
          docker push $(echo "${{ inputs.image }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
          docker push $(echo "${{ inputs.image }}:latest" | tr '[:upper:]' '[:lower:]')