name: Docker Build

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      path:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets: inherit

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Tag
        run: |
          docker build -t ${{ inputs.image }}:${{ github.sha }} ${{ inputs.path }}
          docker tag ${{ inputs.image }}:${{ github.sha }} ${{ inputs.image }}:latest

      - name: Push to GHCR
        run: |
          docker push ${{ inputs.image }}:${{ github.sha }}
          docker push ${{ inputs.image }}:latest