# Shared job template: Docker login
.docker-login:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - echo "🔑 Logging into GitLab Container Registry"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

# Shared job template: Docker build
.docker-build-template:
  extends: .docker-login
  stage: build
  script:
    # Normalize tags to lowercase
    - IMAGE_SHA=$(echo "${CI_REGISTRY_IMAGE}/${SERVICE}:${CI_COMMIT_SHA}" | tr '[:upper:]' '[:lower:]')
    - IMAGE_LATEST=$(echo "${CI_REGISTRY_IMAGE}/${SERVICE}:latest" | tr '[:upper:]' '[:lower:]')
    - IMAGE_BUILD=$(echo "${CI_REGISTRY_IMAGE}/${SERVICE}:build-${CI_PIPELINE_IID}" | tr '[:upper:]' '[:lower:]')

    - echo "🐳 Building $IMAGE_SHA"
    - docker pull "$IMAGE_LATEST" || true
    - docker build --pull --cache-from "$IMAGE_LATEST" -t "$IMAGE_SHA" "$BUILD_PATH"

    # Tag additional variants
    - docker tag "$IMAGE_SHA" "$IMAGE_LATEST"
    - docker tag "$IMAGE_SHA" "$IMAGE_BUILD"

    - echo "📤 Pushing images"
    - docker push "$IMAGE_SHA"
    - docker push "$IMAGE_LATEST"
    - docker push "$IMAGE_BUILD"

# Backend build job (branches only)
backend-build:
  extends: .docker-build-template
  variables:
    SERVICE: "linksphere-backend"
    BUILD_PATH: "./backend"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - backend/**/*

# Frontend build job (branches only)
frontend-build:
  extends: .docker-build-template
  variables:
    SERVICE: "linksphere-frontend"
    BUILD_PATH: "./frontend"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - frontend/**/*
